// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package tcx

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type policyEpCfg struct {
	_                  structs.HostLayout
	EpId               uint64
	Flags              uint32
	Pad                uint32
	TcpEstablishedNs   uint64
	TcpTransitoryNs    uint64
	OtherEstablishedNs uint64
	OtherTransitoryNs  uint64
	FragNs             uint64
	Dir                [2]struct {
		_        structs.HostLayout
		Isolated uint32
		Pad      uint32
		WildPeer struct {
			_ structs.HostLayout
			W [8]uint64
		}
		WildPort struct {
			_ structs.HostLayout
			W [8]uint64
		}
	}
}

type policyFlowKey struct {
	_      structs.HostLayout
	EpId   uint64
	Saddr  [16]uint8
	Daddr  [16]uint8
	Sport  uint16
	Dport  uint16
	Proto  uint8
	Family uint8
	Pad    uint16
}

type policyFlowVal struct {
	_        structs.HostLayout
	LastSeen uint64
	Flags    uint32
	Pad      uint32
}

type policyFragKey struct {
	_      structs.HostLayout
	EpId   uint64
	Saddr  [16]uint8
	Daddr  [16]uint8
	Id     uint32
	Proto  uint8
	Family uint8
	Pad    uint16
}

type policyLpmPortKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Proto     uint8
	Port      [2]uint8
	Pad       uint8
}

type policyLpmV4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [4]uint8
}

type policyLpmV6Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type policyPeerVal struct {
	_     structs.HostLayout
	Rules policyRuleBits
	Flags uint32
	Pad   uint32
}

type policyRuleBits struct {
	_ structs.HostLayout
	W [8]uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	policyMapFlows        = "flows"
	policyMapFrags        = "frags"
	policyMapPeer4Egress  = "peer4_egress"
	policyMapPeer4Ingress = "peer4_ingress"
	policyMapPeer6Egress  = "peer6_egress"
	policyMapPeer6Ingress = "peer6_ingress"
	policyMapPortEgress   = "port_egress"
	policyMapPortIngress  = "port_ingress"
	policyProgMnpEgress   = "mnp_egress"
	policyProgMnpIngress  = "mnp_ingress"
	policyVarCfg          = "cfg"
)

// loadPolicy returns the embedded CollectionSpec for policy.
func loadPolicy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PolicyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load policy: %w", err)
	}

	return spec, err
}

// loadPolicyObjects loads policy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*policyObjects
//	*policyPrograms
//	*policyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPolicyObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPolicy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// policySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type policySpecs struct {
	policyProgramSpecs
	policyMapSpecs
	policyVariableSpecs
}

// policyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type policyProgramSpecs struct {
	MnpEgress  *ebpf.ProgramSpec `ebpf:"mnp_egress"`
	MnpIngress *ebpf.ProgramSpec `ebpf:"mnp_ingress"`
}

// policyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type policyMapSpecs struct {
	Flows        *ebpf.MapSpec `ebpf:"flows"`
	Frags        *ebpf.MapSpec `ebpf:"frags"`
	Peer4Egress  *ebpf.MapSpec `ebpf:"peer4_egress"`
	Peer4Ingress *ebpf.MapSpec `ebpf:"peer4_ingress"`
	Peer6Egress  *ebpf.MapSpec `ebpf:"peer6_egress"`
	Peer6Ingress *ebpf.MapSpec `ebpf:"peer6_ingress"`
	PortEgress   *ebpf.MapSpec `ebpf:"port_egress"`
	PortIngress  *ebpf.MapSpec `ebpf:"port_ingress"`
}

// policyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type policyVariableSpecs struct {
	Cfg *ebpf.VariableSpec `ebpf:"cfg"`
}

// policyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type policyObjects struct {
	policyPrograms
	policyMaps
	policyVariables
}

func (o *policyObjects) Close() error {
	return _PolicyClose(
		&o.policyPrograms,
		&o.policyMaps,
	)
}

// policyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type policyMaps struct {
	Flows        *ebpf.Map `ebpf:"flows"`
	Frags        *ebpf.Map `ebpf:"frags"`
	Peer4Egress  *ebpf.Map `ebpf:"peer4_egress"`
	Peer4Ingress *ebpf.Map `ebpf:"peer4_ingress"`
	Peer6Egress  *ebpf.Map `ebpf:"peer6_egress"`
	Peer6Ingress *ebpf.Map `ebpf:"peer6_ingress"`
	PortEgress   *ebpf.Map `ebpf:"port_egress"`
	PortIngress  *ebpf.Map `ebpf:"port_ingress"`
}

func (m *policyMaps) Close() error {
	return _PolicyClose(
		m.Flows,
		m.Frags,
		m.Peer4Egress,
		m.Peer4Ingress,
		m.Peer6Egress,
		m.Peer6Ingress,
		m.PortEgress,
		m.PortIngress,
	)
}

// policyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type policyVariables struct {
	Cfg *ebpf.Variable `ebpf:"cfg"`
}

// policyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type policyPrograms struct {
	MnpEgress  *ebpf.Program `ebpf:"mnp_egress"`
	MnpIngress *ebpf.Program `ebpf:"mnp_ingress"`
}

func (p *policyPrograms) Close() error {
	return _PolicyClose(
		p.MnpEgress,
		p.MnpIngress,
	)
}

func _PolicyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed policy_bpfel.o
var _PolicyBytes []byte
